#!/bin/bash

#Ubuntu - linux

sudo apt install -y wget vim openjdk-8-jdk opejdk-8-jre


# create a jenkins user and make sure that a home directory is created for it
sudo useradd --create-home jenkins
# set the default shell for jenkins to be bash
sudo usermod --shell /bin/bash jenkins

#Download latest Jenkins WAR
sudo su - jenkins
wget http://updates.jenkins-ci.org/latest/jenkins.war
exit

#Jenkins Service Script

sudo vim /etc/systemd/system/jenkins.service

#Configure 
[Unit]
Description=Jenkins

[Service]
User=jenkins

WorkingDirectory=/home/jenkins

ExecStart=/usr/bin/java -jar /home/jenkins/jenkins.war

[Install]
WantedBy=multi-user.target

#Start the Jenkins Service

sudo systemctl start jenkins
sudo systemctl enable jenkins
